# Don't try to run this file as dataset is no longer in the same folder because of github size limit

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df_trans = pd.read_csv("trans.csv")

In [11]:
df_trans["Timestamp"] = pd.to_datetime(df_trans["Timestamp"])
df_trans["Date"] = df_trans["Timestamp"].dt.date

In [15]:
df_trans['Date'].value_counts()

Date
2022-09-01    1114921
2022-09-02     754449
2022-09-05     482650
2022-09-06     387508
2022-09-04     207430
2022-09-03     207382
2022-09-07        393
2022-09-08        292
2022-09-09        145
2022-09-10         90
2022-09-11         22
2022-09-12          6
2022-09-13          4
2022-09-14          4
Name: count, dtype: int64

In [3]:
df_acc = pd.read_csv("acc.csv")

In [4]:
df_acc.info()

<class 'pandas.DataFrame'>
RangeIndex: 518581 entries, 0 to 518580
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Bank Name       518581 non-null  str
 1   Bank ID         518581 non-null  int64
 2   Account Number  518581 non-null  str
 3   Entity ID       518581 non-null  str
 4   Entity Name     518581 non-null  str
dtypes: int64(1), str(4)
memory usage: 19.8 MB

In [5]:
df_trans.sample(2)

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
2536292,2022/09/05 12:06,1,800A65BB0,11904,806474F00,846.47,US Dollar,846.47,US Dollar,Cheque,0.0
2345741,2022/09/05 02:29,13154,804CEC750,214308,8054902A0,24635.87,Rupee,24635.87,Rupee,Cheque,0.0

In [6]:
df_trans.rename(columns = {'Account':'Sender Account','Account.1':'Receiver Account'},inplace=True)

In [7]:
df_trans.head()

,Timestamp,From Bank,Sender Account,To Bank,Receiver Account,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0.0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0.0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0.0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0.0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0.0

In [8]:
df_acc.head()

,Bank Name,Bank ID,Account Number,Entity ID,Entity Name
0,Portugal Bank #4507,331579,80B779D80,80062E240,Sole Proprietorship #50438
1,Canada Bank #27,210,809D86900,800C998A0,Corporation #33520
2,UK Bank #33,21884,80812BE00,800C47F50,Partnership #35397
3,Germany Bank #4815,32742,81047F300,80096F0B0,Corporation #48813
4,National Bank of Harrisburg,127390,80BD8CF00,800FB8760,Corporation #889

In [52]:
df_acc['Bank ID'].nunique()

30470

In [49]:
df_trans['Is Laundering'].value_counts()

Is Laundering
0    3152270
1       3023
Name: count, dtype: int64

In [10]:
df_trans.isnull().sum()

Timestamp             0
From Bank             0
Sender Account        0
To Bank               0
Receiver Account      0
Amount Received       0
Receiving Currency    0
Amount Paid           0
Payment Currency      0
Payment Format        1
Is Laundering         1
dtype: int64

In [11]:
df_trans.dropna(inplace=True)

In [12]:
df_trans.shape

(3155295, 11)

In [13]:
df_trans['Is Laundering']=df_trans['Is Laundering'].astype(int)

In [14]:
df_trans.head(2)

,Timestamp,From Bank,Sender Account,To Bank,Receiver Account,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0

In [15]:
df_trans.duplicated().sum()

2

In [16]:
df_trans.drop_duplicates(inplace=True)

In [17]:
df_trans.describe()

,From Bank,To Bank,Amount Received,Amount Paid,Is Laundering
count,3.155293e+06,3.155293e+06,3.155293e+06,3.155293e+06,3.155293e+06
mean,4.786503e+04,6.655423e+04,6.597501e+06,5.011216e+06,9.580727e-04
std,8.335488e+04,8.526067e+04,1.057234e+09,8.685679e+08,3.093792e-02
min,1.000000e+00,1.000000e+00,1.000000e-06,1.000000e-06,0.000000e+00
25%,2.110000e+02,4.503000e+03,1.736800e+02,1.747200e+02,0.000000e+00
50%,1.115700e+04,2.161100e+04,1.521700e+03,1.525370e+03,0.000000e+00
75%,2.979400e+04,1.224050e+05,1.429910e+04,1.424205e+04,0.000000e+00
max,3.563030e+05,3.562940e+05,1.046302e+12,1.046302e+12,1.000000e+00

In [18]:
df_acc.isnull().sum()

Bank Name         0
Bank ID           0
Account Number    0
Entity ID         0
Entity Name       0
dtype: int64

In [19]:
df_acc.duplicated().sum()

0

In [20]:
df_trans.to_csv('cleaned_trans.csv',index=False)

In [21]:
df_acc.to_csv('cleaned_acc.csv',index=False)